#! /usr/bin/env python
"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""
import sys

def fibonacci(limit):
    i = 0
    j = 1
    while j < limit:
        i, j = j, i+j
        yield j
    return

def main():
    print sum([f for f in fibonacci(4000000) if f%2==0])

if __name__ == "__main__":
    sys.exit(main())
